### ISSUE TITLE
[BUG] The game stops responding if map cache exists

### ISSUE THREAD

**Issue by RandomGuy45678** [arkhometha/Historical-Project-Mod#229]
**System Information:**
 - Mod Version v0.4.6.3
 - Mod Checksum BRSW
 - Vanilla Checksum YPOI

**Describe the bug**
The windows screen that 'v2game.exe has stopped responding' shows up when the game is opened with the mod. However, clearing Documents\Paradox Interactive\Victoria II\HPM\map\cache fixes this issue. Opening the game with the mod again fills the folder with the cache, which crashes the game the next time it's opened with the mod, though. The crash occurs at the last screen, which says the map is properly initialised.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
The game should go into the main menu as regular.

**Screenshots**
If applicable, add screenshots to help explain your problem. Save games can also be useful.

**Additional context**
In order to fix a different crash, default.map's line of `definitions = "../mod/HPM/map/definition.csv"` was changed to `definitions = "definition.csv"`. The map works perfectly fine when the game _does_ open, however.

**Comment by RandomGuy45678** [comment]
And now it started always crashing, whether the cache is there or not. I haven't changed anything.

**Comment by moretrim** [comment]
> In order to fix a different crash, default.map's line of `definitions = "../mod/HPM/map/definition.csv"` was changed to `definitions = "definition.csv"`. The map works perfectly fine when the game _does_ open, however.

If you do that, I believe the game will be using the unmodded `definition.csv`. Then you get the crash because you’re using the unmodded map definition file together with the mod’s actual map (that’s provided through the other files in `HPM/map`).

If I got this right, this setup has no hope of working: as you might expect, the unmodded `definition.csv` is designed to work with the unmodded map; whereas HPM’s own definition file is designed for the mod’s own map. You have to leave HPM’s `definitions` unchanged, and address whatever issues arise from that.

**Comment by RandomGuy45678** [comment]
It did not give the unmodded definition.csv. However, I haven't looked up how to download Victoria 2 mods when I installed HPM and thus installed them the same way as mods for other Paradox games: by putting it in the user directory in Documents. This could be why definition.csv worked right. The game actually stopped crashing consistently (I have not checked with cache intact), although after looking it up, it is related to the fact that my GPU is old. That is the issue.

When the mod did work, it was running really slow, so I'll just play vanilla from now on.
