### ISSUE TITLE
[BUG] Declining to recognize Paraguay's indepedence as PBC crashes game

### ISSUE THREAD

**Issue by nolovedeepfried** [arkhometha/Historical-Project-Mod#30]
**System Information:**
latest version. Using Solus, running through Proton but I've never had any problems unique to Linux that I have not also found on Windows.

**Describe the bug**
Declining to recognize Paraguay's independence as PBC crashes game. Sometimes.

**To Reproduce**
Pick PBC. 
(Unsure if this part is necessary) Chile didn't declare war on me. Released, annexed (North) Peru, then annexed South Peru (assuming by event)

Decline to recognize Paraguay's independence, game hangs

Loaded the autosave, tried to reproduce - no hang. But it has happened to me on earlier versions as well.

**Comment by arkhometha** [comment]
Hi @nolovedeepfried and thanks for the report. I've tried to reproduce the issue without success, but you mention reproduction is not consistent. I cannot see anything in the event that could cause a crash but alas, it's old stuff, so I've rewritten it to try and guarantee it won't happen again. I cannot guarantee that will not happen because it can be a lot of things (including your OS, though that shouldn't be the case).
Potential fix made in commit https://github.com/arkhometha/Historical-Project-Mod/commit/ef147138aefa7f697c1431129d933611665e9db1
