### ISSUE TITLE
[BUG] Negative social spending

### ISSUE THREAD

**Issue by halcyon-gh** [arkhometha/Historical-Project-Mod#38]
**System Information:**
 - Mod Version: Development branch 5-nov-2019
 - Checksum: DNET

**Describe the bug**
Negative social spending in the pensions category after the "trinket minimum wage" reform

**To Reproduce**
Not sure how to add social reforms using the terminal. See attached save for example.
[Netherlands.zip](https://github.com/arkhometha/Historical-Project-Mod/files/3810061/Netherlands.zip)

**Screenshots**
![social_spending](https://user-images.githubusercontent.com/40493098/68226461-64cf8180-fff2-11e9-8581-7aceb3adf57a.png)

**Comment by arkhometha** [comment]
Hi @halcyon-gh, thanks for the report!

I tried to reproduce the bug without success.
![image](https://user-images.githubusercontent.com/10909718/71603954-a0ed1180-2b5f-11ea-8a4d-7b622b24cb5e.png)

Taking a look at the files, there is nothing that could indicate something is wrong and minimum wage does expenses do not come from the Social Spending slider. Maybe a group of factors are responsible for this, maybe not... until then, I will keep an eye on it. Thanks for the save but I'm terribly sorry I cannot use your save for now, as Development versions move fast. At some point I will dig the development version that was in the 5th of November and I will try to run your save game and try to figure out what could have caused it, but since it appears to be so far an isolated incident, I'm treating it as an in-development changes gone wrong or engine weirdness

**Comment by arkhometha** [comment]
Deserves further exploring. I will try and replicate the issue again.
