### ISSUE TITLE
[BUG] Fiume in Event 31510: A Greater Austrian Destiny

### ISSUE THREAD

**Issue by Kyriau** [arkhometha/Historical-Project-Mod#42]
Version 0.4.5 (?), downloaded 11 September 2019

Selecting the third option (Independence) releases Fiume. This appears to be unintended, as Fiume is an Austrian core. Germany is not given Fiume as a core.

Selecting the second option (Limited Autonomy) does not release Fiume. This appears to be the intended behaviour. However, Germany is still not given Fiume as a core, which appears to be unintended. Furthermore, triggering the event a second time and again selecting the second option does release Fiume (there is no situation where this will occur in proper play, but I believe it suggests the problem is with how the game sequences the actions in the event).

Note: I haven't tested this for naturally occurring 31510, only via console at the 1 January 1836 bookmark.

**Comment by Kyriau** [comment]
On further investigation, you also get different results for Eisenstadt between the second and third choices. These are the only two provinces that are cores of both Austria and Hungary.

**Comment by arkhometha** [comment]
Thanks for the report! This issues is fixed in commit https://github.com/arkhometha/Historical-Project-Mod/commit/afcb7198a1fc2988e2f568283b260f76301f74a4

I want to rework how the "Greater Germany" event chain works at some point. For now, both the 2nd and the 3rd option have effects that add German cores to Fiume and Eisenstadt  and at the same time remove Hungarian cores from there. In my tests, that fixed the problem.
