### ISSUE TITLE
[BUG] Annexation of Schlesvig Event can fire despite Scandinavia already being forced

### ISSUE THREAD

**Issue by Wolfenswan** [arkhometha/Historical-Project-Mod#54]
**System Information:**
 - 0.4.6

**Describe the bug**
The event gives denmark cores for aabrena & flensburg and starts a war between slesvig-holstein & denmark. Even if denmark no longer exists the cores will be added and slesvig-h. will be locked in a never-ending war with a non-existent Denmark.

Related issue: If s.-h. is a puppet of scandinavia it will call Sca. to war against the non-existent Denmark.

**Expected**
Event should either be blocked if Denmark does not exist or add Scandinavia cores.

**Screenshots**
![20191230195227_1](https://user-images.githubusercontent.com/2631302/71596098-8eaeab80-2b3e-11ea-8084-8f047a7df135.jpg)
![20191230195727_1](https://user-images.githubusercontent.com/2631302/71596117-9d955e00-2b3e-11ea-8da0-e69540d51ecf.jpg)

**Comment by arkhometha** [comment]
Thanks for the report! This issues is fixed in commit https://github.com/arkhometha/Historical-Project-Mod/commit/afcb7198a1fc2988e2f568283b260f76301f74a4

Scandinavia should be better integrated in the Schleswig-Holstein question now. The war should start against Scandinavia when appropriate and add cores to them.
