### ISSUE TITLE
Purchasing a ironclad decreases level of naval base you can build[BUG]

### ISSUE THREAD

**Issue by karrot1** [arkhometha/Historical-Project-Mod#58]
**System Information:**
 - Mod Version: Not sure, I pulled from the dev repo yesterday
 - Mod Checksum RIBP

**Describe the bug**
Buying a ironclad sets the level of naval base you can build to 1, even if you have higher naval tech than that. This is fixed by saving and reloading.

**To Reproduce**
Steps to reproduce the behavior.
Buy a ironclad when you have the tech to build level 2 naval bases, and now you can only build level 1 bases.

**Expected behavior**
I expected to just get a free ironclad.

**Comment by arkhometha** [comment]
Hi @karrot1, thanks for the report. I confirm I've been able to reproduce the bug and it is fixed in commit https://github.com/arkhometha/Historical-Project-Mod/commit/f238ac1c85e6940498f3e0677f4ba74fde54f7e9

It's related to another fix made to solve the vanilla bug that happened with spawned units not being able to move from port.
