### ISSUE TITLE
[BUG] Artisan discrepancies

### ISSUE THREAD

**Issue by halcyon-gh** [arkhometha/Historical-Project-Mod#66]
**System Information:**
version 0.4.6

**Describe the bug**
When looking through the production setup for artisans, there are some settings that seem strange to me. Some might be intended, but I list all that don't follow the overall pattern.

1. Artisans producing clipper_convoy, fabric, and liquor make a loss at the default good prices.
2. Artisan profit for regular_clothes is low compared to other goods (£6 vs £15-£25)
3. Artisans producing ammunition and liquor use different inputs than the corresponding factories
4. Artisans producing ammunition, canned_food, liquor, and wine produce 150% or more output than the corresponding factories

**Comment by arkhometha** [comment]
Hi @halcyon-gh, thanks for another report! Good catch. The issues are fixed in commit https://github.com/arkhometha/Historical-Project-Mod/commit/be39d4e7b2abfb755a98cde18490ad2c9f2fff43
Do keep in mind there's still no "base" profitability for goods, so issue 2 is a bit subjective. I'd like to, at some point, divide the goods better in informal categories (basic consumer goods like furniture and clothes, industrial and constructions goods such as steel and machine parts, luxury goods, furniture goods, etc) and assign each one a "window" of base profitability. While that does not happen, things go on being a bit chaotic on the base profitability part - though I do try and keep it making sense, so consumer goods will have less base profitability than luxury goods, for example.
