### ISSUE TITLE
[BUG] Switzerland keeps sending out alliance but then instantly breaks it

### ISSUE THREAD

**Issue by pingerdactyl** [arkhometha/Historical-Project-Mod#72]
**System Information:**
 - Mod Version - 0.4.6 Beta 2
 - Mod Checksum - PETE

**Describe the bug**
Switzerland keeps sending out alliance but then instantly breaks it

**To Reproduce**
Play as any country around switzerland such as france or german

**Expected behavior**
Switzerland should not send out an alliance or should not break them instantly because it will reduce their prestige needlessly

**Comment by arkhometha** [comment]
Hi @pingerdactyl, thanks for the report! What you see is expected behaviour - Switzerland is a neutral country. Unfortunately, I cannot enforce that neutrality any other way than a decision they take to break alliances as soon as they form them, they are in-game restrictions. After a few refusals of your part, or after a few breakups, they should stop sending alliance requests.
