### ISSUE TITLE
[BUG] Endless Vassalisation Event

### ISSUE THREAD

**Issue by B-Leo** [arkhometha/Historical-Project-Mod#76]
Straightforward bug as described in title.

Win a war with taking vassal CB and have to welcome them into my empire every day with no chance to do anything else. See the following savefile. I used the git sync version of HPM.

https://mega.nz/#!6SJRQIpJ!KtheZ3-X6t5Egxg9U8HiSxoYmqM07uK7E6UzsGNOY5w

**Comment by arkhometha** [comment]
Hi @B-Leo, thanks for the report. Since you didn't provide a checksum, I can't be sure by what you mean by "git sync version" of HPM. I'm assuming it's the master branch - the latest beta, checksum PETE. If that is the case, the issue was reported and fixed here https://github.com/arkhometha/Historical-Project-Mod/issues/68

I'm finishing testing the latest version and 0.4.6 should could out of beta soon - though it will be incompatible with games started in the beta version, unfortunately.

**Comment by B-Leo** [comment]
Ah I see. Yeah I only pulled the master branch instead of the development branch so this fix was not included. Thanks for your help.
