### ISSUE TITLE
[BUG] Inventions description missing

### ISSUE THREAD

**Issue by pingerdactyl** [arkhometha/Historical-Project-Mod#77]
**System Information:**
 - Mod Version - 0.4.6 beta 2
 - Mod Checksum - PETE

**Describe the bug**
Luxury goods inventions description not written

**To Reproduce**
Research Late Classical Theory then discover Industrial Luxury Furniture Production and Luxury Clothes Production

**Expected behavior**
The inventions should have a proper description

**Screenshots**
![Luxury goods description missing](https://user-images.githubusercontent.com/45688791/72806764-c1fbda80-3ca5-11ea-88b5-142ed6b3a189.png)

**Comment by arkhometha** [comment]
Hi @pingerdactyl, thanks for the report. I really appreciate it. This has been reported here https://github.com/arkhometha/Historical-Project-Mod/issues/59 and fixed here https://github.com/arkhometha/Historical-Project-Mod/commit/be39d4e7b2abfb755a98cde18490ad2c9f2fff43

Overall, the [development](https://github.com/arkhometha/Historical-Project-Mod/tree/Development) branch is quite ahead of the latest beta release, and I'm planning to bring 4.6 out of its beta soonish - today or tomorrow. I'm just running the last test game, though because of changes to inventions it won't be compatible with games started during the 4.6 beta.
