### ISSUE TITLE
Issues with new version of HPM

### ISSUE THREAD

**Issue by NorvalR** [arkhometha/Historical-Project-Mod#82]
1) Wallachia is producing oil in 1848 - Tirgoviste province

2) The -25% unemployment subsidies from Lassie Faire, work... probably not the way you think. It appears to pay the government money when there is no unemployment benefits but there are unemployed people. Similarly, it makes the government create magic money for to pay for benefits. I think this is fair given the -25% to -10% import cost nerf to the LF economic system.

**Comment by arkhometha** [comment]
Hi @NorvalR, thanks for the report.

1. Its intended. There's also a province producing rubber - to avoid prices shooting up too much, since demand is there from the start. It doesn't help much but earlier tests to make the need for oil/rubber unlock with the inventions that flip these places were not that successful. I might try my hand at that again in the future.

2. Sorry about that, old piece of code that remained unsupervised. That was fixed in the [Hotfix 1](https://github.com/arkhometha/Historical-Project-Mod/releases/tag/0.4.6.1).
