### ISSUE TITLE
[BUG] Scandinavia can't annex a puppet Finland

### ISSUE THREAD

**Issue by Fireiy** [arkhometha/Historical-Project-Mod#87]
**System Information:**
 - Mod Version v0.4.6 Hotfix 1
 - Mod Checksum KAQP
 - Vanilla Checksum WNVU

**Describe the bug**
When you form Scandinavia and promote Nordism, Finland will never offer their annexation.

**To Reproduce**
Form Scandinavia, promote Nordism, have Finland as your puppet and in your sphere.

**Expected behavior**
As a cultural union, Scandinavia should be able to peacefully annex puppets of their culture group that are in their sphere of influence.

**Additional context**
It seems that a cultural union tag for Scandinavia is missing in the cultures file. I added it and it within two years Finland petitioned for annexation.

**Comment by mk-over** [comment]
Since Scandinavia is not a union tag, in the same sense as Italy and Germany, members of the culture group will never petition for annexation. They are not really a proper union tag and Finland was not part of the plans. I don't see a young Finnish state willingly submitting itself to someone else.

With that said, Russia can force integration through decision. I don't see why Scandinavia wouldn't be able to do it with a puppet - but they are not doing it willingly, so no petitions.

**Comment by arkhometha** [comment]
Since Scandinavia is not a union tag, in the same sense as Italy and Germany, members of the culture group will never petition for annexation. It's not really a proper union tag and Finland was not part of the plans. I don't see a young Finnish state willingly submitting itself to someone else.

With that said, Russia can force integration through decision. I don't see why Scandinavia wouldn't be able to do it with a puppet - but they are not doing it willingly, so no petitions.

**Comment by Fireiy** [comment]
At the same time though Iceland was also not a part of the plans but can be turned into cores through promoting Nordism. Perhaps that decision should be part of the process of forcing Finland to join?
